version: "3"
services:
  nginx-swarm:
    build: ./docker/${CONTAINER}
    image: ${ORGANIZATION}/${CONTAINER}:${BUILD_TAG}
    container_name: ${CONTAINER}
    restart: always
    environment:
      - PROXY_SERVICE_NAME=${PROXY_SERVICE_NAME}
      - PROXY_DOMAIN=${PROXY_DOMAIN}
      - PROXY_EMAIL=${PROXY_EMAIL}
      - PROXY_AUTH_USER=${PROXY_AUTH_USER}
      - PROXY_AUTH_PASS=${PROXY_AUTH_PASS}
    networks:
      - ingress
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    # service deployment
    deploy:
      replicas: 1
      # labels: [endpoint=${BUILD_TAG}]
      # service resource management
      resources:
        # Hard limit - Docker does not allow to allocate more
        limits:
          cpus: '0.25'
          memory: 512M
        # Soft limit - Docker makes best effort to return to it
        reservations:
          cpus: '0.25'
          memory: 256M
      # service restart policy
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      # service update configuration
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
